### PR TITLE
First draft adding net452, net461 and netcoreapp2.1 support. Also Ser…

### PR DESCRIPTION
**Pull request by driekus77**
…ilog version bump to 2.8.0.

@lucascebertin I sort of guested your answer. This PR adds support, in the same way as I did for Serilog.Sinks.Oracle, to Serilog.Sinks.Burst.

Notes: Skipped 1 unit test: Could not find why it failed.

Comments are welcome!

### CODE REVIEW

**Comment by lucascebertin** [comment]
After a lot of time spent, finally I understood why the test breaks.
Looks like FakeItEasy is not ThreadSafe with the counter that is used to verify the amount of invokes.
I removed the fake and created my own counter with `Interlocked.Incremente(ref counter)`.

After that, 20 test executions and all passing.
Can I push this fix to my own repo and ask you to test again?

**Comment by driekus77** [comment]
Yes let me test the test

**Comment by driekus77** [comment]
@lucascebertin 

Please wait with commiting this PR! I discovered that it looks like the MSIL/Any CPU dll is always installed/used.

I've asked a question about this on StackOverflow: https://stackoverflow.com/questions/55591105/how-to-check-if-my-c-sharp-app-is-using-the-right-platform-specific-dll-from-nug

For your information,

**Comment by lucascebertin** [comment]
No problem, I'll proceed with the test fix while we wait for the answer

**Comment by lucascebertin** [comment]
Now, the tests execution looks consistent but I had introduced merge conflicts in your commit :(

**Comment by driekus77** [comment]
I will fix this merge conflict and also test it.

Also I was mistakingly adding x64, x86 to your project builds. According to the answer at S.O.: https://stackoverflow.com/questions/55591105/how-to-check-if-my-c-sharp-app-is-using-the-right-platform-specific-dll-from-nug/55592337#55592337

We only need Any CPU (MSIL) to build and distribute. 
I will change both PR's for this.

**Comment by driekus77** [comment]
@lucascebertin 

I've run the unittests multiple times with your fix ands its working fine now.

Also removed x86 and x64 builds (Both in project files and build.cake) and removed .netcoreapp2.1 in favour of .netstandard2.0 (as you sugested in the oracle review comments)

Let me know if more work is needed!

Kind regards,
Henry

**Comment by lucascebertin** [comment]
Let's go ahead now!
I'll merge and publish!

**Pull request merged**
